CONSUL_FOLDER=./consul
CONSUL_BIN=${CONSUL_FOLDER}/consul
CONSUL_STDOUT=${CONSUL_FOLDER}/consul.stdout
CONSUL_DATA_DIR=${CONSUL_FOLDER}/consul-data

VAULT_FOLDER=./vault
VAULT_BIN=${VAULT_FOLDER}/vault
VAULT_STDOUT=${VAULT_FOLDER}/vault.stdout
VAULT_INIT_OUTPUT=${VAULT_FOLDER}/vault_init.out

export VAULT_ADDR=http://127.0.0.1:8200
