VAULT_DIR=/opt/vault
VAULT_LOG_DIR=/var/log/vault
VAULT_CONF_DIR=${VAULT_DIR}/conf
VAULT_BIN_DIR=${VAULT_DIR}/bin
VAULT_ROLE_DIR=${VAULT_DIR}/role

CONSUL_BIN=${VAULT_BIN_DIR}/consul
CONSUL_STDOUT=${VAULT_LOG_DIR}/consul.stdout
CONSUL_DATA_DIR=${VAULT_DIR}/consul-data

VAULT_BIN=${VAULT_BIN_DIR}/vault
VAULT_STDOUT=${VAULT_LOG_DIR}/vault.stdout
VAULT_INIT_OUTPUT=${VAULT_TOKEN_DIR}/vault_init.out
VAULT_TOKEN_CONFIG=${VAULT_CONF_DIR}/token.conf

export VAULT_ADDR=http://127.0.0.1:8200
